# # version: '2'
# services:
  web:
    build: .
    volumes:
      - ./:/app
      - ./:/node_modules
    ports:
      - '3001:3000'
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27018:27017'
